conditions: v1

git:
  depth: 99999

language: java

jdk:
  - openjdk11

addons:
  apt:
    update: true
  chrome: stable
  firefox: latest

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache/

before_install:
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - export CHROME_BIN=/usr/bin/google-chrome

install: true

jobs:
  include:
    - script: ./gradlew check --no-daemon --console=plain
      name: "Check"
    - script: ./gradlew chrome_headless --fail-fast --no-daemon --console=plain -i
      name: "Chrome1"
    - script: ./gradlew chrome_headless --fail-fast --no-daemon --console=plain -i
      name: "Chrome2"
    - script: ./gradlew chrome_headless --fail-fast --no-daemon --console=plain -i
      name: "Chrome3"
    - script: ./gradlew chrome_headless --fail-fast --no-daemon --console=plain -i
      name: "Chrome4"
    - script: ./gradlew chrome_headless --fail-fast --no-daemon --console=plain -i
      name: "Chrome5"
    - script: ./gradlew chrome_headless --fail-fast --no-daemon --console=plain -i
      name: "Chrome6"
    - script: ./gradlew chrome_headless --fail-fast --no-daemon --console=plain -i
      name: "Chrome7"
    - script: ./gradlew chrome_headless --fail-fast --no-daemon --console=plain -i
      name: "Chrome8"

after_failure: "./.upload_reports.sh"
